# Generated by Django 4.1.5 on 2023-01-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='user_email',
            field=models.CharField(max_length=100),
        ),
    ]
