# Generated by Django 4.1.5 on 2023-01-20 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('Feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('Rating', models.IntegerField()),
                ('Description', models.CharField(max_length=100)),
                ('user_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
